<a href="https://colab.research.google.com/github/Srikhanth14/Data_Analysis_Projects/blob/main/HealthCare_Resource_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import the Necessary Libraries**

In [4]:
import pandas as pd
import numpy as np

# **Data Collection and Processing**

In [5]:
#Loading the Datasets
data = pd.read_csv("modified_healthcare_dataset.csv")

In [6]:
# Display first three rows of the dataset
data.head(3)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
0,Bobby Jackson,19,Female,AB+,Infections,2024-01-31,Matthew Smith,Northwestern Memorial Hospital,Blue Cross,2212.272701,328,Emergency,2024-02-07,Azithromycin,Normal,7
1,Leslie Terry,15,Female,B-,Flu,2019-08-20,Samantha Davies,UI Health (University of Illinois Hospital),UnitedHealthcare,3185.161388,265,Emergency,2019-08-22,Tamiflu,Abnormal,2
2,Danny Smith,50,Female,A+,Cancer,2022-09-22,Tiffany Mitchell,UI Health (University of Illinois Hospital),Blue Cross,72055.214065,205,Elective,2022-10-30,Cisplatin,Inconclusive,38


In [7]:
# Display last four rows of the dataset
data.tail(4)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
55496,Kyle Perez,63,Male,A+,Heart Disease,2020-01-23,Taylor Sullivan,UI Health (University of Illinois Hospital),Medicare,26828.223456,316,Emergency,2020-03-07,Statins,Abnormal,44
55497,Heather Wang,28,Female,O+,Asthma,2020-07-13,Joe Jacobs DVM,Northwestern Memorial Hospital,Cigna,6041.030866,347,Elective,2020-07-16,Montelukast,Normal,3
55498,Jennifer Jones,75,Male,O+,Cancer,2019-05-25,Kimberly Curry,UChicago Medicine,Aetna,44495.656362,321,Emergency,2019-07-11,Methotrexate,Abnormal,47
55499,James Garcia,53,Female,O+,Diabetes,2024-04-02,Dennis Warren,Loyola University Medical Center,Cigna,15953.455966,448,Emergency,2024-04-12,Insulin,Abnormal,10


In [8]:
#Display the Sample of any 2 rows from the dataset
data.sample(2)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
50822,Elizabeth Oconnell,60,Female,AB-,Obesity,2021-01-31,Mitchell Stewart,UChicago Medicine,Cigna,5614.754871,122,Elective,2021-02-03,Orlistat,Abnormal,3
5540,Kelli Wallace,60,Female,O+,Obesity,2023-12-28,Jessica Nixon,Northwestern Memorial Hospital,Medicare,7594.864870,441,Elective,2024-01-02,Orlistat,Normal,5


In [9]:
#Print the Dimensions of the dataset
print("Number of Rows: ", data.shape[0])
print("Number of Columns: ", data.shape[1])

Number of Rows:  55500
Number of Columns:  16


In [10]:
#Displaying all column names in the Dataset
for col in data.columns:
  print(col)

Name
Age
Gender
Blood Type
Medical Condition
Date of Admission
Doctor
Hospital
Insurance Provider
Billing Amount
Room Number
Admission Type
Discharge Date
Medication
Test Results
Length of Stay


In [11]:
#Checking the Data type of Columns in the Dataset
data.dtypes.to_frame(name="Data_Type")

,Data_Type
Name,object
Age,int64
Gender,object
Blood Type,object
Medical Condition,object
Date of Admission,object
Doctor,object
Hospital,object
Insurance Provider,object
Billing Amount,float64


In [12]:
# Checking any null values present in the each column
if data.isnull().sum().sum() == 0:
  print("No null values present in the dataset")
else:
  print("Null values present in the dataset")

No null values present in the dataset


In [13]:
print(data.isnull().sum())

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
Length of Stay        0
dtype: int64


In [14]:
#Checking any duplicate values present in the Dataset
if data.duplicated().sum() == 0:
  print("Duplicate values doesn't exist in the dataset")
else:
  print("Duplicate values exist in the dataset")

Duplicate values doesn't exist in the dataset


In [15]:
#Statistical Summary of the Dataset
data.describe()

,Age,Billing Amount,Room Number,Length of Stay
count,55500.000000,55500.000000,55500.000000,55500.000000
mean,48.001622,21835.044635,301.134829,17.841009
std,21.105827,23574.413594,115.243069,20.272294
min,5.000000,500.220989,101.000000,1.000000
25%,32.000000,4195.525741,202.000000,4.000000
50%,50.000000,11089.537763,302.000000,8.000000
75%,65.000000,35887.703406,401.000000,28.000000
max,90.000000,99997.797977,500.000000,89.000000


In [16]:
#Overview of the Dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Name                55500 non-null  object 
 1   Age                 55500 non-null  int64  
 2   Gender              55500 non-null  object 
 3   Blood Type          55500 non-null  object 
 4   Medical Condition   55500 non-null  object 
 5   Date of Admission   55500 non-null  object 
 6   Doctor              55500 non-null  object 
 7   Hospital            55500 non-null  object 
 8   Insurance Provider  55500 non-null  object 
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64  
 11  Admission Type      55500 non-null  object 
 12  Discharge Date      55500 non-null  object 
 13  Medication          55500 non-null  object 
 14  Test Results        55500 non-null  object 
 15  Length of Stay      55500 non-null  int64  
dtypes: f

In [17]:
#Identifying the Total unique values in Each Column
data.nunique()

,0
Name,40235
Age,86
Gender,2
Blood Type,8
Medical Condition,8
Date of Admission,1827
Doctor,40341
Hospital,4
Insurance Provider,5
Billing Amount,55500


In [18]:
print("Frequency of Each Categorical Variables",'\n')
Categorical_Target_Columns = ["Gender","Blood Type", "Medical Condition", "Doctor", "Hospital", "Insurance Provider", "Admission Type", "Medication", "Test Results"]

for categorical_columns in Categorical_Target_Columns:
    print(data[categorical_columns].value_counts())
    print("-"*50)

Frequency of Each Categorical Variables 

Gender
Female    27955
Male      27545
Name: count, dtype: int64
--------------------------------------------------
Blood Type
O+     15696
A+     15573
B+      5457
AB-     4485
B-      4408
O-      3341
A-      3301
AB+     3239
Name: count, dtype: int64
--------------------------------------------------
Medical Condition
Flu              7046
Diabetes         7005
Obesity          6994
Cancer           6940
Asthma           6908
Heart Disease    6900
Alzheimer’s      6861
Infections       6846
Name: count, dtype: int64
--------------------------------------------------
Doctor
Michael Smith      27
John Smith         22
Robert Smith       22
Michael Johnson    20
James Smith        20
                   ..
Keith Ortiz         1
Timothy Chapman     1
Terri Collins       1
Jill Jacobson       1
Scott Coleman       1
Name: count, Length: 40341, dtype: int64
--------------------------------------------------
Hospital
Northwestern Memorial Hospita

In [19]:
print("Distribution of Categorical Variables in Percentage",'\n')
for categorical_columns in Categorical_Target_Columns:
    print(data[categorical_columns].value_counts(normalize=True)*100)
    print("-"*50)

Distribution of Categorical Variables in Percentage 

Gender
Female    50.369369
Male      49.630631
Name: proportion, dtype: float64
--------------------------------------------------
Blood Type
O+     28.281081
A+     28.059459
B+      9.832432
AB-     8.081081
B-      7.942342
O-      6.019820
A-      5.947748
AB+     5.836036
Name: proportion, dtype: float64
--------------------------------------------------
Medical Condition
Flu              12.695495
Diabetes         12.621622
Obesity          12.601802
Cancer           12.504505
Asthma           12.446847
Heart Disease    12.432432
Alzheimer’s      12.362162
Infections       12.335135
Name: proportion, dtype: float64
--------------------------------------------------
Doctor
Michael Smith      0.048649
John Smith         0.039640
Robert Smith       0.039640
Michael Johnson    0.036036
James Smith        0.036036
                     ...   
Keith Ortiz        0.001802
Timothy Chapman    0.001802
Terri Collins      0.001802
Jill Ja

# **Data Cleaning and Pre-Processing**

In [20]:
#Converting Date Columns to Date Type
data["Date of Admission"] = pd.to_datetime(data["Date of Admission"])
data["Discharge Date"] = pd.to_datetime(data["Discharge Date"])

In [21]:
print(data[["Date of Admission","Discharge Date"]].dtypes)

Date of Admission    datetime64[ns]
Discharge Date       datetime64[ns]
dtype: object


In [22]:
data[["Date of Admission","Discharge Date"]].sample(2)

,Date of Admission,Discharge Date
6080,2019-10-03,2019-11-15
15547,2021-11-22,2021-12-01


In [23]:
#Admission and Discharge Date Validation
Date_Validation = data['Discharge Date'] > data['Date of Admission']
print("Are all discharge date valid: ", Date_Validation.all())
print("Total Invalid rows in Date_Validation: ",(~Date_Validation).sum())

Are all discharge date valid:  True
Total Invalid rows in Date_Validation:  0


In [24]:
#Length of Stay Validation
Calculated_Length_Of_Stay = (data['Discharge Date'] - data['Date of Admission']).dt.days
Length_Of_Stay_Validation = data['Length of Stay']== Calculated_Length_Of_Stay
print("Does Length of Stay match the Calculated Length_Of_Stay numbers: ", Length_Of_Stay_Validation.all())
print("Total Invalid rows in Length_of_Stay_Validation: ",(~Length_Of_Stay_Validation).sum())

Does Length of Stay match the Calculated Length_Of_Stay numbers:  True
Total Invalid rows in Length_of_Stay_Validation:  0


In [25]:
#Billing Amount Validation
Billing_Validation = data['Billing Amount']>0
print("Does Billing Amount is greater than zero: ", Billing_Validation.all())
print("Total Invalid rows in Billing Amount: ",(~Billing_Validation).sum())

Does Billing Amount is greater than zero:  True
Total Invalid rows in Billing Amount:  0


In [26]:
#Age Validation
Age_Validation = data['Age'].between(0,100)
print("Are all ages within the valid ranges: ", Age_Validation.all())
print("Total Invalid Values in Ages: ",(~Age_Validation).sum())

Are all ages within the valid ranges:  True
Total Invalid Values in Ages:  0


In [27]:
#Cross checking the consistency of Categorical Target Columns
Categorical_Target_Columns = ["Gender","Blood Type", "Medical Condition", "Hospital", "Insurance Provider", "Admission Type"]

for categorical_columns in Categorical_Target_Columns:
    print(categorical_columns)
    print(data[categorical_columns].unique())
    print("-"*50)

Gender
['Female' 'Male']
--------------------------------------------------
Blood Type
['AB+' 'B-' 'A+' 'O+' 'O-' 'AB-' 'A-' 'B+']
--------------------------------------------------
Medical Condition
['Infections' 'Flu' 'Cancer' 'Asthma' 'Heart Disease' 'Alzheimer’s'
 'Diabetes' 'Obesity']
--------------------------------------------------
Hospital
['Northwestern Memorial Hospital'
 'UI Health (University of Illinois Hospital)' 'UChicago Medicine'
 'Loyola University Medical Center']
--------------------------------------------------
Insurance Provider
['Blue Cross' 'UnitedHealthcare' 'Aetna' 'Cigna' 'Medicare']
--------------------------------------------------
Admission Type
['Emergency' 'Elective' 'Routine' 'Urgent']
--------------------------------------------------


# **Feature Engineering**

In [28]:
#Extracting the day, month and year from the Admission Date
data['Admission Day'] = data['Date of Admission'].dt.day_name()
data['Admission Month'] = data['Date of Admission'].dt.month
data['Admission Year'] = data['Date of Admission'].dt.year

In [29]:
print("Unique values in Admission Year")
print(data["Admission Year"].unique())

Unique values in Admission Year
[2024 2019 2022 2020 2023 2021]


In [30]:
print("Unique values in Admission Week Day")
print(data["Admission Day"].unique())

Unique values in Admission Week Day
['Wednesday' 'Tuesday' 'Thursday' 'Monday' 'Sunday' 'Friday' 'Saturday']


In [31]:
print("Unique values in Admission Month")
print(data["Admission Month"].unique())

Unique values in Admission Month
[ 1  8  9 11 12  7  5  4 10  6  3  2]


In [32]:
print("Frequency values in Admission Year", '\n')
print(data.groupby("Admission Year").size().sort_values(ascending=False))

Frequency values in Admission Year 

Admission Year
2020    11285
2023    11026
2022    11017
2021    10931
2019     7387
2024     3854
dtype: int64


In [33]:
print("Frequency values in Admission Month", '\n')
print(data.groupby("Admission Month").size().sort_values(ascending=False))

Frequency values in Admission Month 

Admission Month
8     4832
7     4812
6     4699
1     4692
10    4678
3     4672
12    4649
5     4599
11    4548
9     4546
4     4518
2     4255
dtype: int64


In [34]:
print("Frequency values in Admission Week Day", '\n')
print(data.groupby("Admission Day").size().sort_values(ascending=False))

Frequency values in Admission Week Day 

Admission Day
Thursday     7989
Tuesday      7982
Wednesday    7950
Sunday       7920
Saturday     7901
Friday       7892
Monday       7866
dtype: int64


#**One-Hot Encoding**

In [35]:
#Converting Required Categorical Features to Numeric using One-Hot Encoding
Encoded_Data=pd.get_dummies(data, columns=["Gender","Blood Type","Medical Condition","Hospital","Insurance Provider","Admission Day"],drop_first=True,dtype=int)
Encoded_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 41 columns):
 #   Column                                                Non-Null Count  Dtype         
---  ------                                                --------------  -----         
 0   Name                                                  55500 non-null  object        
 1   Age                                                   55500 non-null  int64         
 2   Date of Admission                                     55500 non-null  datetime64[ns]
 3   Doctor                                                55500 non-null  object        
 4   Billing Amount                                        55500 non-null  float64       
 5   Room Number                                           55500 non-null  int64         
 6   Admission Type                                        55500 non-null  object        
 7   Discharge Date                                        55500 non-null  dateti

In [36]:
print(Encoded_Data.columns)

Index(['Name', 'Age', 'Date of Admission', 'Doctor', 'Billing Amount',
       'Room Number', 'Admission Type', 'Discharge Date', 'Medication',
       'Test Results', 'Length of Stay', 'Admission Month', 'Admission Year',
       'Gender_Male', 'Blood Type_A-', 'Blood Type_AB+', 'Blood Type_AB-',
       'Blood Type_B+', 'Blood Type_B-', 'Blood Type_O+', 'Blood Type_O-',
       'Medical Condition_Asthma', 'Medical Condition_Cancer',
       'Medical Condition_Diabetes', 'Medical Condition_Flu',
       'Medical Condition_Heart Disease', 'Medical Condition_Infections',
       'Medical Condition_Obesity', 'Hospital_Northwestern Memorial Hospital',
       'Hospital_UChicago Medicine',
       'Hospital_UI Health (University of Illinois Hospital)',
       'Insurance Provider_Blue Cross', 'Insurance Provider_Cigna',
       'Insurance Provider_Medicare', 'Insurance Provider_UnitedHealthcare',
       'Admission Day_Monday', 'Admission Day_Saturday',
       'Admission Day_Sunday', 'Admission Day_Thu

# **Label Encoding**

In [37]:
#Encoding the Target Feature by using Label Encoding i,e Mapping Function
Admission_Type_Mapping = {'Emergency': 0, 'Elective': 1, 'Urgent': 2,'Routine':3}
Encoded_Data['Admission Type'] = Encoded_Data['Admission Type'].map(Admission_Type_Mapping)

In [38]:
Encoded_Data['Admission Type'].value_counts()

,count
Admission Type,
0,20104
1,13280
2,11816
3,10300


In [39]:
Encoded_Data.sample(2)

,Name,Age,Date of Admission,Doctor,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,...,Insurance Provider_Blue Cross,Insurance Provider_Cigna,Insurance Provider_Medicare,Insurance Provider_UnitedHealthcare,Admission Day_Monday,Admission Day_Saturday,Admission Day_Sunday,Admission Day_Thursday,Admission Day_Tuesday,Admission Day_Wednesday
51208,Julie Smith,65,2020-08-01,Mrs. Vanessa Jordan,73389.380291,266,0,2020-08-29,Methotrexate,Inconclusive,...,0,0,0,0,0,1,0,0,0,0
44462,Sarah Schroeder,22,2022-05-17,Katrina Johnson,5945.831645,424,1,2022-05-21,Albuterol,Normal,...,0,0,0,0,0,0,0,0,1,0


# **Model Selection**

In [40]:
from sklearn.model_selection import train_test_split   #Splitting the Data
from sklearn.linear_model import LogisticRegression    #Logistic Regression
from sklearn.tree import DecisionTreeClassifier        #Decision Tree
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier    #Random Forest Classification, Gradient Boosting Classifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score  #Model Evaluation Parameters

In [41]:
#Splitting the Training and Target Features
x=Encoded_Data.drop(['Name','Date of Admission', 'Doctor','Billing Amount','Room Number','Admission Type','Discharge Date', 'Medication','Test Results', 'Length of Stay'], axis=1)
y=Encoded_Data['Admission Type']

In [42]:
print(x.shape,y.shape)

(55500, 31) (55500,)


In [43]:
#Training and Testing the Data
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=0.2, random_state=2, stratify=y)

In [44]:
print(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)

(44400, 31) (11100, 31) (44400,) (11100,)


In [45]:
Models={
'Logistic Regression':LogisticRegression(max_iter=3000,solver='saga'),
'Decision Tree':DecisionTreeClassifier(),
'Random Forest':RandomForestClassifier(random_state=2)
 }


# **Model Evaluation**

In [46]:
#Creating an Empty Result Set
Results = []

In [47]:
#Training and Evaluating the Each Model
for model_name, model in Models.items():
      model.fit(X_train, Y_train)
      Y_pred = model.predict(X_test)

      accuracy = accuracy_score(Y_test, Y_pred)*100
      precision = precision_score(Y_test, Y_pred, average='weighted',zero_division=0)*100
      recall = recall_score(Y_test, Y_pred, average='weighted',zero_division=0)*100
      f1 = f1_score(Y_test, Y_pred, average='weighted',zero_division=0)*100

      Results.append([model_name, accuracy,precision,recall,f1])


In [48]:
# Create a DataFrame to store results
Results_df = pd.DataFrame(Results, columns=['Model', 'Accuracy', 'Precision', 'Recall', 'F1-Score'])
Results_df

,Model,Accuracy,Precision,Recall,F1-Score
0,Logistic Regression,45.297297,27.574165,45.297297,33.764592
1,Decision Tree,32.639640,33.117365,32.639640,32.852652
2,Random Forest,41.225225,36.872034,41.225225,37.537292


In [49]:
#Classification Report and Confusion Matrix for Each Model
for model_name, model in Models.items():
  model.fit(X_train, Y_train)
  Y_pred = model.predict(X_test)
  print(f"Classification Report for {model_name}:")
  print(classification_report(Y_test, Y_pred))
  print(f"Confusion Matrix for {model_name}:")
  print(confusion_matrix(Y_test, Y_pred))
  print("-"*50)

Classification Report for Logistic Regression:
              precision    recall  f1-score   support

           0       0.44      0.87      0.59      4021
           1       0.49      0.57      0.52      2656
           2       0.00      0.00      0.00      2363
           3       0.00      0.00      0.00      2060

    accuracy                           0.45     11100
   macro avg       0.23      0.36      0.28     11100
weighted avg       0.28      0.45      0.34     11100

Confusion Matrix for Logistic Regression:
[[3514  506    0    1]
 [1142 1514    0    0]
 [1874  488    0    1]
 [1450  609    1    0]]
--------------------------------------------------
Classification Report for Decision Tree:
              precision    recall  f1-score   support

           0       0.43      0.41      0.42      4021
           1       0.35      0.35      0.35      2656
           2       0.23      0.24      0.23      2363
           3       0.22      0.22      0.22      2060

    accuracy       

In [50]:
#Evaluating the Importance of Features by using the Random Forest Model
Random_Forest_model = Models['Random Forest']
importances = (Random_Forest_model.feature_importances_)*100
feature_importances = pd.DataFrame({'Feature': x.columns, 'Importance': importances}).sort_values(by='Importance', ascending=False)
print(feature_importances)

                                              Feature  Importance
0                                                 Age   21.620510
1                                     Admission Month   15.269335
2                                      Admission Year   11.005430
3                                         Gender_Male    3.898197
17                          Medical Condition_Obesity    3.560677
9                                       Blood Type_O+    2.882941
18            Hospital_Northwestern Memorial Hospital    2.676961
19                         Hospital_UChicago Medicine    2.583594
20  Hospital_UI Health (University of Illinois Hos...    2.433679
21                      Insurance Provider_Blue Cross    2.367574
23                        Insurance Provider_Medicare    2.213449
24                Insurance Provider_UnitedHealthcare    2.199929
22                           Insurance Provider_Cigna    2.199357
29                              Admission Day_Tuesday    1.983042
30        

In [54]:
Random_Forest_Models ={
    'RF_Leaf1': RandomForestClassifier(n_estimators=300,random_state=2,max_depth=10,min_samples_split=10,min_samples_leaf=1),
    'RF_Leaf2': RandomForestClassifier(n_estimators=300,random_state=2,max_depth=10,min_samples_split=10,min_samples_leaf=2),
    'RF_Leaf3': RandomForestClassifier(n_estimators=300,random_state=2,max_depth=10,min_samples_split=10,min_samples_leaf=5),
    'RF_Leaf4': RandomForestClassifier(n_estimators=300,random_state=2,max_depth=20,min_samples_split=20,min_samples_leaf=10)
    }

Random_Results=[]

for model_name, model in Random_Forest_Models.items():
      model.fit(X_train, Y_train)
      Y_pred = model.predict(X_test)
      accuracy = accuracy_score(Y_test, Y_pred)*100
      precision = precision_score(Y_test, Y_pred, average='weighted',zero_division=0)*100
      recall = recall_score(Y_test, Y_pred, average='weighted',zero_division=0)*100
      f1 = f1_score(Y_test, Y_pred, average='weighted',zero_division=0)*100
      Random_Results.append([model_name, accuracy,precision,recall,f1])

# Create a DataFrame to store results
Results_Random_df = pd.DataFrame(Random_Results, columns=['Model', 'Accuracy','precision','recall','f1'])
Results_Random_df

,Model,Accuracy,precision,recall,f1
0,RF_Leaf1,45.306306,27.668062,45.306306,33.721671
1,RF_Leaf2,45.288288,27.693278,45.288288,33.694089
2,RF_Leaf3,45.297297,27.729053,45.297297,33.677094
3,RF_Leaf4,45.567568,40.450176,45.567568,36.210198


In [55]:
#Classification Report and Confusion Matrix for Each Model
for model_name, model in Random_Forest_Models.items():
  model.fit(X_train, Y_train)
  Y_pred = model.predict(X_test)
  print(f"Classification Report for {model_name}:")
  print(classification_report(Y_test, Y_pred))
  print(f"Confusion Matrix for {model_name}:")
  print(confusion_matrix(Y_test, Y_pred))
  print("-"*50)

Classification Report for RF_Leaf1:
              precision    recall  f1-score   support

           0       0.44      0.88      0.59      4021
           1       0.49      0.55      0.52      2656
           2       0.00      0.00      0.00      2363
           3       0.00      0.00      0.00      2060

    accuracy                           0.45     11100
   macro avg       0.23      0.36      0.28     11100
weighted avg       0.28      0.45      0.34     11100

Confusion Matrix for RF_Leaf1:
[[3557  464    0    0]
 [1184 1472    0    0]
 [1897  466    0    0]
 [1470  589    1    0]]
--------------------------------------------------


/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Classification Report for RF_Leaf2:
              precision    recall  f1-score   support

           0       0.44      0.89      0.59      4021
           1       0.49      0.55      0.52      2656
           2       0.00      0.00      0.00      2363
           3       0.00      0.00      0.00      2060

    accuracy                           0.45     11100
   macro avg       0.23      0.36      0.28     11100
weighted avg       0.28      0.45      0.34     11100

Confusion Matrix for RF_Leaf2:
[[3568  453    0    0]
 [1197 1459    0    0]
 [1906  457    0    0]
 [1479  581    0    0]]
--------------------------------------------------


/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Classification Report for RF_Leaf3:
              precision    recall  f1-score   support

           0       0.44      0.89      0.59      4021
           1       0.50      0.54      0.52      2656
           2       0.00      0.00      0.00      2363
           3       0.00      0.00      0.00      2060

    accuracy                           0.45     11100
   macro avg       0.23      0.36      0.28     11100
weighted avg       0.28      0.45      0.34     11100

Confusion Matrix for RF_Leaf3:
[[3586  435    0    0]
 [1214 1442    0    0]
 [1914  449    0    0]
 [1481  579    0    0]]
--------------------------------------------------


/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Classification Report for RF_Leaf4:
              precision    recall  f1-score   support

           0       0.46      0.82      0.59      4021
           1       0.47      0.61      0.53      2656
           2       0.30      0.01      0.02      2363
           3       0.34      0.06      0.10      2060

    accuracy                           0.46     11100
   macro avg       0.39      0.37      0.31     11100
weighted avg       0.40      0.46      0.36     11100

Confusion Matrix for RF_Leaf4:
[[3294  597   29  101]
 [ 953 1617    5   81]
 [1720  554   19   70]
 [1247  675   10  128]]
--------------------------------------------------


In [56]:
Gradient_Models ={
    'GB_Leaf1': GradientBoostingClassifier(n_estimators=300,learning_rate=0.01,random_state=2),
    'GB_Leaf2': GradientBoostingClassifier(n_estimators=300,learning_rate=0.05,random_state=2),
    'GB_Leaf3': GradientBoostingClassifier(n_estimators=300,learning_rate=0.10,random_state=2),
    'GB_Leaf4': GradientBoostingClassifier(n_estimators=300,learning_rate=0.20,random_state=2)
    }

Gradient_Models_Result=[]

for model_name, model in Gradient_Models.items():
      model.fit(X_train, Y_train)
      Y_pred = model.predict(X_test)
      accuracy = accuracy_score(Y_test, Y_pred)*100
      precision = precision_score(Y_test, Y_pred, average='weighted',zero_division=0)*100
      recall = recall_score(Y_test, Y_pred, average='weighted',zero_division=0)*100
      f1 = f1_score(Y_test, Y_pred, average='weighted',zero_division=0)*100
      Gradient_Models_Result.append([model_name, accuracy,precision,recall,f1])

# Create a DataFrame to store results
Gradient_Models_df = pd.DataFrame(Gradient_Models_Result, columns=['Model', 'Accuracy','precision','recall','f1'])
Gradient_Models_df

,Model,Accuracy,precision,recall,f1
0,GB_Leaf1,45.279279,32.696856,45.279279,33.993149
1,GB_Leaf2,45.126126,37.812460,45.126126,35.490544
2,GB_Leaf3,45.369369,39.087591,45.369369,36.630134
3,GB_Leaf4,44.882883,38.336313,44.882883,37.179380


In [57]:
#Classification Report and Confusion Matrix for Each Model
for model_name, model in Gradient_Models.items():
  model.fit(X_train, Y_train)
  Y_pred = model.predict(X_test)
  print(f"Classification Report for {model_name}:")
  print(classification_report(Y_test, Y_pred))
  print(f"Confusion Matrix for {model_name}:")
  print(confusion_matrix(Y_test, Y_pred))
  print("-"*50)

Classification Report for GB_Leaf1:
              precision    recall  f1-score   support

           0       0.44      0.86      0.58      4021
           1       0.48      0.59      0.53      2656
           2       0.00      0.00      0.00      2363
           3       0.28      0.01      0.01      2060

    accuracy                           0.45     11100
   macro avg       0.30      0.36      0.28     11100
weighted avg       0.33      0.45      0.34     11100

Confusion Matrix for GB_Leaf1:
[[3445  561    0   15]
 [1082 1570    0    4]
 [1826  528    0    9]
 [1407  642    0   11]]
--------------------------------------------------


/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Classification Report for GB_Leaf2:
              precision    recall  f1-score   support

           0       0.46      0.81      0.58      4021
           1       0.46      0.62      0.53      2656
           2       0.24      0.00      0.01      2363
           3       0.28      0.05      0.08      2060

    accuracy                           0.45     11100
   macro avg       0.36      0.37      0.30     11100
weighted avg       0.38      0.45      0.35     11100

Confusion Matrix for GB_Leaf2:
[[3244  654   23  100]
 [ 930 1657    5   64]
 [1689  575   11   88]
 [1256  700    7   97]]
--------------------------------------------------
Classification Report for GB_Leaf3:
              precision    recall  f1-score   support

           0       0.46      0.80      0.58      4021
           1       0.46      0.62      0.53      2656
           2       0.25      0.01      0.02      2363
           3       0.33      0.08      0.12      2060

    accuracy                           0.45   